# yaml-language-server: $schema=https://server-vms.develop.taylordb.ai/apps/config-schema/v1

version: 1

project: blank

runtime:
  type: node
  version: 20
  packageManager: pnpm

services:
  client:
    workDir: .
    install:
      commands:
        - pnpm install
    dev:
      command: pnpm dev
      port: 5173
      env:
        vars:
          NODE_ENV: production
          VITE_TAYLORDB_BASE_ID: vars.TAYLORDB_SERVER_ID
          VITE_TAYLORDB_BASE_URL: vars.TAYLORDB_EXTERNAL_BASE_URL
      
    start:
      command: pnpm preview --port 5173
      port: 5173
      env:
        vars:
          VITE_TRPC_URL: routing.server.url
      
    build:
      commands:
        - pnpm build
      env:
        vars:
          VITE_TRPC_URL: routing.server.url

taylordb:
  types:
    - output: src/lib/taylordb.types.ts
      format: typescript
      onChange:
        - pnpm lint

preview:
  service: client

routing:
  - path: /
    service: client
